<?php
session_start(); require '../config/database.php'; require '../lib_phase8.php';
if(!isset($_SESSION['user']) || $_SESSION['user']['role']!=='teacher'){header('Location: ../login.php');exit;}
$u=$_SESSION['user'];$tid=teacherId($pdo,(int)$u['id']);
$q=$pdo->prepare('SELECT t.department FROM teachers t WHERE t.id=?');$q->execute([$tid]);$teacher=$q->fetch()?:['department'=>''];
$q=$pdo->prepare("SELECT ta.id assignment_id,ta.term,ta.academic_year,ta.section_id,s.*,p.name program_name,p.level,p.specialization,sec.name section_name FROM teacher_assignments ta JOIN subjects s ON s.id=ta.subject_id JOIN programs p ON p.id=ta.program_id LEFT JOIN sections sec ON sec.id=ta.section_id WHERE ta.teacher_id=? AND ta.active=1 ORDER BY FIELD(p.level,'HSSC','BS','ADP'),p.name,ta.term,s.name,sec.name");$q->execute([$tid]);$subjects=$q->fetchAll();
$pageTitle='Teacher Dashboard'; require '../includes/header.php';?>
<div class="container py-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bold mb-1">Teacher Dashboard</h2><p class="text-muted mb-0">Welcome, <?=htmlspecialchars($u['name'])?></p></div><a class="btn btn-outline-danger" href="../logout.php">Logout</a></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card shadow-sm border-0"><div class="card-body"><small class="text-muted">Department</small><h5><?=htmlspecialchars($teacher['department'])?></h5></div></div></div><div class="col-md-4"><div class="card shadow-sm border-0"><div class="card-body"><small class="text-muted">Assigned Subjects</small><h3><?=count($subjects)?></h3></div></div></div></div>
<div class="alert alert-info">You can enter attendance and marks only for the exact class/program assignments given by the administrator.</div>
<div class="card shadow-sm border-0"><div class="card-body"><h5 class="fw-bold">My Assigned Subjects</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Program</th><th>Subject</th><th>Code</th><th>Year / Semester</th><th>Section</th><th>CH</th><th>Action</th></tr></thead><tbody><?php foreach($subjects as $s):?><tr><td><?=htmlspecialchars($s['level'].' — '.$s['program_name'])?></td><td><?=htmlspecialchars($s['name'])?></td><td><?=htmlspecialchars($s['code'])?></td><td><?=htmlspecialchars($s['term'])?></td><td><?=htmlspecialchars($s['section_name']?:'All Sections')?></td><td><?=htmlspecialchars($s['credit_hours'])?></td><td><a class="btn btn-sm btn-primary" href="attendance.php?assignment_id=<?=$s['assignment_id']?>">Attendance</a> <a class="btn btn-sm btn-outline-primary" href="marks.php?assignment_id=<?=$s['assignment_id']?>">Marks</a></td></tr><?php endforeach;if(!$subjects):?><tr><td colspan="7" class="text-muted">No class/subject assignments. Ask the administrator to assign your classes and subjects.</td></tr><?php endif;?></tbody></table></div></div></div></div><?php require '../includes/footer.php';?>
