<?php
session_start(); require 'config/database.php'; require 'lib_security.php';
$msg=$error='';
$programs=$pdo->query("SELECT * FROM programs WHERE active=1 ORDER BY FIELD(level,'HSSC','BS','ADP'),name")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){ verifyCsrf();
 $name=trim($_POST['name']); $father=trim($_POST['father_name']); $cnic=trim($_POST['cnic']); $email=trim($_POST['email']); $phone=trim($_POST['phone']); $program=(int)$_POST['program_id']; $session=trim($_POST['admission_session']??''); $marks=(float)$_POST['previous_marks']; $total=(float)$_POST['previous_total'];
 if($name===''||$father===''||$email===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||$program<1||$total<=0||!preg_match('/^\d{4}-\d{2}$/',$session)){$error='Please fill all required fields correctly.';} else {
  $appNo='IMCB-'.date('Y').'-'.str_pad((string)random_int(1,99999),5,'0',STR_PAD_LEFT);
  try{$q=$pdo->prepare('INSERT INTO admission_applications(application_no,name,father_name,cnic,email,phone,program_id,previous_marks,previous_total,merit_score,status,admission_session) VALUES(?,?,?,?,?,?,?,?,?,? ,"pending",?)');$q->execute([$appNo,$name,$father,$cnic,$email,$phone,$program,$marks,$total,$total>0?round(($marks/$total)*100,2):0,$session]);$msg="Application submitted successfully. Application No: $appNo";}catch(Throwable $e){$error='Could not submit application. CNIC/email may already be registered.';}
 }
}
$pageTitle='Online Admission'; require 'includes/header.php';
?>
<div class="container py-5"><div class="row justify-content-center"><div class="col-lg-9"><div class="card shadow-sm border-0"><div class="card-body p-4 p-lg-5"><div class="d-flex justify-content-between align-items-center"><div><h2 class="fw-bold">Online Admission Application</h2><p class="text-muted">IMCB F-10/4 — College, BS & ADP admissions</p></div><a href="index.php" class="btn btn-outline-secondary">Home</a></div><?php if($msg):?><div class="alert alert-success mt-3"><?=htmlspecialchars($msg)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger mt-3"><?=htmlspecialchars($error)?></div><?php endif;?><form method="post" class="row g-3 mt-2"><?php echo csrfField(); ?><div class="col-md-6"><label class="form-label">Applicant Name *</label><input name="name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Father / Guardian Name *</label><input name="father_name" class="form-control" required></div><div class="col-md-4"><label class="form-label">CNIC / B-Form</label><input name="cnic" class="form-control" placeholder="Optional"></div><div class="col-md-4"><label class="form-label">Email *</label><input name="email" type="email" class="form-control" required></div><div class="col-md-4"><label class="form-label">Phone</label><input name="phone" class="form-control"></div><div class="col-md-3"><label class="form-label">Admission Session *</label><input name="admission_session" class="form-control" value="<?=date('Y').'-'.substr((string)(date('Y')+1),-2)?>" required></div><div class="col-md-3"><label class="form-label">Apply For *</label><select name="program_id" class="form-select" required><option value="">Select program</option><?php foreach($programs as $p):?><option value="<?=$p['id']?>"><?=$p['level']?> — <?=htmlspecialchars($p['name'])?><?= $p['specialization']?' — '.htmlspecialchars($p['specialization']):''?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Previous Marks *</label><input name="previous_marks" type="number" step="0.01" min="0" class="form-control" required></div><div class="col-md-3"><label class="form-label">Total Marks *</label><input name="previous_total" type="number" step="0.01" min="1" class="form-control" required></div><div class="col-12"><div class="alert alert-info mb-0">Merit score is calculated automatically as previous marks ÷ total marks × 100. Final eligibility and merit rules must be verified against the applicable official admission policy.</div></div><div class="col-12"><button class="btn btn-primary px-4">Submit Application</button></div></form></div></div></div></div></div><?php require 'includes/footer.php';?>
