<?php
session_start();require 'config/database.php';
if(!isset($_SESSION['user'])){header('Location: login.php');exit;}
$role=$_SESSION['user']['role'];$sid=(int)($_GET['student_id']??0);
if($role==='student'){$q=$pdo->prepare('SELECT id FROM students WHERE user_id=?');$q->execute([$_SESSION['user']['id']]);$sid=(int)$q->fetchColumn();}
if($sid<1){exit('Student not found.');}
$q=$pdo->prepare("SELECT st.*,u.name,u.email,p.level,p.name program_name,p.specialization,s.name section_name,c.card_no,c.issue_date,c.valid_until,c.status card_status FROM students st JOIN users u ON u.id=st.user_id JOIN programs p ON p.id=st.program_id LEFT JOIN sections s ON s.id=st.section_id LEFT JOIN student_id_cards c ON c.student_id=st.id WHERE st.id=?");$q->execute([$sid]);$s=$q->fetch();if(!$s)exit('Student not found.');
if(!$s['card_no']){ if($role==='student') exit('ID card has not been issued yet. Please contact the administration.'); exit('Student ID card has not been issued yet.'); }
$pageTitle='Student ID Card';require 'includes/header.php';?><div class="container py-5"><div class="d-flex justify-content-between mb-3"><h2>Student ID Card</h2><button class="btn btn-primary" onclick="window.print()">Print</button></div><div class="id-card mx-auto"><div class="id-head"><div class="fw-bold fs-4">IMCB F-10/4</div><div>STUDENT IDENTITY CARD</div></div><div class="id-body"><div class="photo-box">PHOTO</div><div><h4 class="mb-1"><?=htmlspecialchars($s['name'])?></h4><p class="mb-1"><strong>Roll No:</strong> <?=htmlspecialchars($s['roll_no'])?></p><p class="mb-1"><strong>Program:</strong> <?=htmlspecialchars($s['program_name'])?></p><p class="mb-1"><strong>Term:</strong> <?=htmlspecialchars($s['semester_or_year'])?></p><p class="mb-1"><strong>Section:</strong> <?=htmlspecialchars($s['section_name']??'—')?></p></div></div><div class="id-foot"><span><?=htmlspecialchars($s['card_no']??'Not issued')?></span><span>Valid: <?=htmlspecialchars($s['valid_until']??'—')?></span></div></div><div class="text-center text-muted mt-3">Official card details should be confirmed by the institution before production use.</div></div><style>.id-card{max-width:720px;border:2px solid #173f68;border-radius:18px;overflow:hidden;box-shadow:0 10px 30px rgba(0,0,0,.12)}.id-head{background:#173f68;color:#fff;padding:18px 25px}.id-body{display:flex;gap:25px;padding:30px}.photo-box{width:130px;height:160px;border:2px dashed #aaa;display:flex;align-items:center;justify-content:center;color:#777}.id-foot{display:flex;justify-content:space-between;padding:14px 25px;background:#f3f6fa;font-weight:600}@media print{.portal-nav,.btn,.text-muted,footer{display:none!important}.id-card{box-shadow:none}}</style><?php require 'includes/footer.php';?>
