<?php
session_start();require 'config/database.php';require 'lib_results.php';require 'lib_phase8.php';
if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='student'){header('Location: login.php');exit;}
$q=$pdo->prepare('SELECT st.*,u.name,u.email,p.level,p.name program_name,p.specialization FROM students st JOIN users u ON u.id=st.user_id JOIN programs p ON p.id=st.program_id WHERE st.user_id=?');$q->execute([$_SESSION['user']['id']]);$student=$q->fetch();if(!$student)exit('Student profile not found.');
$term=$student['semester_or_year'];$status=resultStatus($pdo,(int)$student['id'],$term);$result=studentResult($pdo,(int)$student['id'],$term);$overall=studentOverall($pdo,(int)$student['id']);
$showResult=in_array($status,['published','locked'],true);
$atts=attendanceSummary($pdo,(int)$student['id'],$term);
$aud=$pdo->quote(strtolower($student['level']));$n=$pdo->query("SELECT title,body,audience,published_at FROM notices WHERE audience='all' OR audience='students' OR audience=$aud ORDER BY published_at DESC LIMIT 6")->fetchAll();
$pageTitle='Student Portal';require 'includes/header.php';?>
<div class="container-fluid"><div class="row"><aside class="col-md-2 sidebar py-4"><h6 class="px-3 text-muted">STUDENT MENU</h6><a class="active" href="student.php">Dashboard</a><a href="transcript.php">Transcript / GPA History</a><a href="#result">Results & GPA</a><a href="#attendance">Attendance</a><a href="#notices">Notices</a><a href="fees.php">Fee Challans</a><a href="documents.php">My Documents</a><a href="id_card.php">My ID Card</a><a href="logout.php">Logout</a></aside><main class="col-md-10 p-4"><div class="d-flex justify-content-between"><div><h2 class="fw-bold">Welcome, <?=htmlspecialchars($student['name'])?></h2><p class="text-muted"><?=htmlspecialchars($student['program_name'].' · '.$student['semester_or_year'])?></p></div><div class="d-flex gap-2 align-self-start"><span class="badge text-bg-primary"><?=htmlspecialchars($student['roll_no'])?></span><?php if($showResult):?><a target="_blank" class="btn btn-sm btn-primary" href="result_card.php?term=<?=urlencode($term)?>">Print Result Card</a><?php endif;?></div></div>
<?php if(!$showResult):?><div class="alert alert-warning"><strong>Result status:</strong> <?=htmlspecialchars(ucfirst($status))?>. Your result will appear here after the administration publishes it.</div><?php endif;?>
<div class="row g-3"><div class="col-md-3"><div class="card stat-card shadow-sm p-3"><small>Current GPA</small><h2><?= $showResult?number_format($result['gpa'],2):'—'?></h2></div></div><div class="col-md-3"><div class="card stat-card shadow-sm p-3"><small>Attendance Subjects</small><h2><?=count($atts)?></h2></div></div><div class="col-md-3"><div class="card stat-card shadow-sm p-3"><small>Overall GPA</small><h2><?= $showResult?number_format($overall['gpa'],2):'—'?></h2></div></div><div class="col-md-3"><div class="card stat-card shadow-sm p-3"><small>Program</small><h6 class="mt-2 mb-0"><?=htmlspecialchars($student['level'])?></h6></div></div></div>
<div id="result" class="card shadow-sm border-0 mt-4"><div class="card-body"><div class="d-flex justify-content-between"><h5 class="fw-bold">Results & GPA</h5><?php if($showResult):?><a href="transcript.php" class="btn btn-sm btn-outline-primary">View Transcript</a><?php endif;?></div><?php if($showResult):?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Code</th><th>Subject</th><th>Credit</th><th>Marks %</th><th>Grade</th><th>GP</th></tr></thead><tbody><?php foreach($result['rows'] as $r):?><tr><td><?=htmlspecialchars($r['code'])?></td><td><?=htmlspecialchars($r['name'])?></td><td><?=number_format($r['credit_hours'],1)?></td><td><?=number_format($r['percent'],2)?>%</td><td><span class="badge text-bg-<?=($r['letter_grade']==='F'?'danger':'success')?>"><?=htmlspecialchars($r['letter_grade'])?></span></td><td><?=number_format($r['grade_point'],2)?></td></tr><?php endforeach;if(!$result['rows']):?><tr><td colspan="6" class="text-muted">No result data.</td></tr><?php endif;?></tbody></table></div><?php else:?><p class="text-muted mb-0">Result is not published yet.</p><?php endif;?></div></div>
<div id="attendance" class="card shadow-sm border-0 mt-4"><div class="card-body"><h5 class="fw-bold">Attendance</h5><div class="table-responsive"><table class="table"><thead><tr><th>Subject</th><th>Present</th><th>Absent</th><th>Leave</th><th>Attendance</th><th>Status</th></tr></thead><tbody><?php foreach($atts as $r):$low=$r['total']>0&&$r['percentage']<75;?><tr><td><?=htmlspecialchars($r['code'].' — '.$r['name'])?></td><td><?=$r['present']?></td><td><?=$r['absent']?></td><td><?=$r['leave']?></td><td><?=number_format($r['percentage'],1)?>%</td><td><span class="badge text-bg-<?=$low?'danger':'success'?>"><?=$low?'Below 75%':'OK'?></span></td></tr><?php endforeach;if(!$atts):?><tr><td colspan="6" class="text-muted">No attendance records yet.</td></tr><?php endif;?></tbody></table></div><div class="small text-muted">Attendance warning threshold shown by the portal is 75%. Confirm the official institutional rule before production use.</div></div></div>
<div id="notices" class="card shadow-sm border-0 mt-4 mb-4"><div class="card-body"><h5 class="fw-bold">Recent Notices</h5><?php foreach($n as $notice):?><div class="border-bottom py-2"><strong><?=htmlspecialchars($notice['title'])?></strong><div class="small text-muted"><?=htmlspecialchars($notice['published_at'])?></div><div><?=nl2br(htmlspecialchars($notice['body']))?></div></div><?php endforeach;if(!$n):?><p class="text-muted mb-0">No notices.</p><?php endif;?></div></div>
</main></div></div><?php require 'includes/footer.php';?>