<?php
session_start(); require '../config/database.php'; require '../lib_security.php';
if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='admin'){header('Location: ../login.php');exit;}
if(isset($_POST['action'])){ verifyCsrf();
  $id=(int)$_POST['id']; $status=$_POST['status']; $remarks=trim($_POST['remarks']??''); $docs=$_POST['document_status']??'pending'; $docRemarks=trim($_POST['document_remarks']??'');
  if(in_array($status,['pending','verified','shortlisted','accepted','rejected'],true) && in_array($docs,['pending','verified','rejected'],true)){
    $q=$pdo->prepare('UPDATE admission_applications SET status=?,remarks=?,document_status=?,document_remarks=?,verified_at=IF(? IN ("verified","shortlisted","accepted"),NOW(),verified_at) WHERE id=?');
    $q->execute([$status,$remarks,$docs,$docRemarks,$status,$id]);
  }
  header('Location: admissions.php'); exit;
}
$rows=$pdo->query('SELECT a.*,p.level,p.name program_name FROM admission_applications a JOIN programs p ON p.id=a.program_id ORDER BY a.merit_score DESC,a.created_at ASC')->fetchAll();
$pageTitle='Admissions'; require '../includes/header.php';
?>
<div class="container py-4"><div class="d-flex justify-content-between"><div><h2>Admissions & Merit List</h2><p class="text-muted">Review applications, verify documents and manage merit status.</p></div><div><a href="registration.php" class="btn btn-primary me-2">Student Registration</a><a href="../admin.php" class="btn btn-outline-secondary">Dashboard</a></div></div>
<div class="card shadow-sm mt-3"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Merit</th><th>Application</th><th>Applicant</th><th>Program</th><th>Marks</th><th>Status</th><th>Document Verification / Action</th></tr></thead><tbody>
<?php foreach($rows as $r):?><tr><td><strong><?=number_format((float)$r['merit_score'],2)?>%</strong></td><td><?=htmlspecialchars($r['application_no'])?><br><small><?=htmlspecialchars($r['admission_session']??'')?></small></td><td><?=htmlspecialchars($r['name'])?><br><small><?=htmlspecialchars($r['email'])?></small></td><td><?=$r['level']?> — <?=htmlspecialchars($r['program_name'])?></td><td><?=htmlspecialchars($r['previous_marks'].' / '.$r['previous_total'])?></td><td><span class="badge text-bg-secondary"><?=htmlspecialchars($r['status'])?></span><?php if(!empty($r['student_id'])):?><br><span class="badge text-bg-success mt-1">Registered</span><?php endif;?></td><td><form method="post" class="row g-1"><?php echo csrfField(); ?><input type="hidden" name="id" value="<?=$r['id']?>"><div class="col-lg-3"><select name="document_status" class="form-select form-select-sm"><option value="pending" <?=$r['document_status']==='pending'?'selected':''?>>Docs pending</option><option value="verified" <?=$r['document_status']==='verified'?'selected':''?>>Docs verified</option><option value="rejected" <?=$r['document_status']==='rejected'?'selected':''?>>Docs rejected</option></select></div><div class="col-lg-3"><select name="status" class="form-select form-select-sm"><option value="pending" <?=$r['status']==='pending'?'selected':''?>>Pending</option><option value="verified" <?=$r['status']==='verified'?'selected':''?>>Verified</option><option value="shortlisted" <?=$r['status']==='shortlisted'?'selected':''?>>Shortlisted</option><option value="accepted" <?=$r['status']==='accepted'?'selected':''?>>Accepted</option><option value="rejected" <?=$r['status']==='rejected'?'selected':''?>>Rejected</option></select></div><div class="col-lg-2"><input name="document_remarks" value="<?=htmlspecialchars($r['document_remarks']??'')?>" class="form-control form-control-sm" placeholder="Doc remarks"></div><div class="col-lg-2"><input name="remarks" value="<?=htmlspecialchars($r['remarks']??'')?>" class="form-control form-control-sm" placeholder="Remarks"></div><div class="col-lg-2"><button name="action" value="update" class="btn btn-sm btn-primary w-100">Save</button></div></form></td></tr><?php endforeach;?>
<?php if(!$rows):?><tr><td colspan="7" class="text-center text-muted py-4">No applications yet.</td></tr><?php endif;?></tbody></table></div></div></div><?php require '../includes/footer.php'; ?>
