<?php
session_start();require '../config/database.php'; require '../lib_security.php';require '../lib_documents.php';
if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='admin'){header('Location: ../login.php');exit;}
$types=documentTypes();$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){ verifyCsrf();
 $id=(int)($_POST['id']??0);$status=$_POST['status']??'';$remarks=trim($_POST['remarks']??'');
 if(!in_array($status,['verified','rejected'],true)){$msg='Invalid status.';}else{$q=$pdo->prepare('UPDATE student_documents SET status=?,remarks=?,verified_at=NOW() WHERE id=?');$q->execute([$status,$remarks,$id]);$msg='Document status updated.';}
}
$q=$pdo->query("SELECT d.*,st.roll_no,u.name,p.name program_name FROM student_documents d JOIN students st ON st.id=d.student_id JOIN users u ON u.id=st.user_id JOIN programs p ON p.id=st.program_id ORDER BY d.uploaded_at DESC");$docs=$q->fetchAll();
$pageTitle='Document Verification';require '../includes/header.php';?>
<div class="container-fluid"><div class="row"><aside class="col-md-2 sidebar py-4"><h6 class="px-3 text-muted">ADMIN MENU</h6><a href="../admin.php">Dashboard</a><a class="active" href="documents.php">Document Verification</a><a href="registration.php">Student Registration</a><a href="../students.php">Students</a><a href="../dashboard.php">My Portal</a></aside><main class="col-md-10 p-4"><div class="d-flex justify-content-between"><div><h2 class="fw-bold">Document Verification</h2><p class="text-muted">Review uploaded student documents.</p></div></div><?php if($msg):?><div class="alert alert-info"><?=htmlspecialchars($msg)?></div><?php endif;?><div class="card shadow-sm border-0"><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Student</th><th>Roll No</th><th>Program</th><th>Document</th><th>Status</th><th>Review</th></tr></thead><tbody><?php foreach($docs as $d):?><tr><td><?=htmlspecialchars($d['name'])?></td><td><?=htmlspecialchars($d['roll_no'])?></td><td><?=htmlspecialchars($d['program_name'])?></td><td><a target="_blank" href="../document_download.php?id=<?=$d['id']?>"><?=htmlspecialchars($types[$d['document_type']]??$d['document_type'])?></a><div class="small text-muted"><?=htmlspecialchars($d['file_name'])?></div></td><td><span class="badge text-bg-<?=($d['status']==='verified'?'success':($d['status']==='rejected'?'danger':'warning'))?>"><?=htmlspecialchars(ucfirst($d['status']))?></span></td><td><form method="post" class="d-flex gap-2"><?php echo csrfField(); ?><input type="hidden" name="id" value="<?=$d['id']?>"><select name="status" class="form-select form-select-sm"><option value="verified">Verify</option><option value="rejected">Reject</option></select><input name="remarks" class="form-control form-control-sm" placeholder="Remarks" value="<?=htmlspecialchars($d['remarks']??'')?>"><button class="btn btn-sm btn-primary">Save</button></form></td></tr><?php endforeach;if(!$docs):?><tr><td colspan="6" class="text-muted">No uploaded documents.</td></tr><?php endif;?></tbody></table></div></div></div></main></div></div><?php require '../includes/footer.php';?>
